conda activate mci
# CUDA_VISIBLE_DEVICES=7 python compressed_model.py --prune_method wanda --sparsity_ratio 0.00 
# CUDA_VISIBLE_DEVICES=7 python compressed_model.py --prune_method wanda --sparsity_ratio 0.05
# CUDA_VISIBLE_DEVICES=7 python compressed_model.py --prune_method wanda --sparsity_ratio 0.10
# CUDA_VISIBLE_DEVICES=7 python compressed_model.py --prune_method wanda --sparsity_ratio 0.20
# CUDA_VISIBLE_DEVICES=7 python compressed_model.py --prune_method wanda --sparsity_ratio 0.30
# CUDA_VISIBLE_DEVICES=7 python compressed_model.py --prune_method wanda --sparsity_ratio 0.40
# CUDA_VISIBLE_DEVICES=7 python compressed_model.py --prune_method wanda --sparsity_ratio 0.50
# CUDA_VISIBLE_DEVICES=7 python compressed_model.py --prune_method wanda --sparsity_ratio 0.60
# CUDA_VISIBLE_DEVICES=7 python compressed_model.py --prune_method wanda --sparsity_ratio 0.15
# CUDA_VISIBLE_DEVICES=7 python compressed_model.py --prune_method wanda --sparsity_ratio 0.25
# CUDA_VISIBLE_DEVICES=7 python compressed_model.py --prune_method wanda --sparsity_ratio 0.35
# CUDA_VISIBLE_DEVICES=7 python compressed_model.py --prune_method wanda --sparsity_ratio 0.45
# CUDA_VISIBLE_DEVICES=7 python compressed_model.py --prune_method wanda --sparsity_ratio 0.55
# CUDA_VISIBLE_DEVICES=7 python compressed_model.py --prune_method wanda --sparsity_ratio 0.65
# CUDA_VISIBLE_DEVICES=7 python compressed_model.py --prune_method wanda --sparsity_ratio 0.70
# CUDA_VISIBLE_DEVICES=7 python compressed_model.py --prune_method wanda --sparsity_ratio 0.75
# CUDA_VISIBLE_DEVICES=7 python compressed_model.py --prune_method wanda --sparsity_ratio 0.80

# CUDA_VISIBLE_DEVICES=6 python compressed_model.py --prune_method sparsegpt --sparsity_ratio 0.00 
# CUDA_VISIBLE_DEVICES=6 python compressed_model.py --prune_method sparsegpt --sparsity_ratio 0.05
# CUDA_VISIBLE_DEVICES=6 python compressed_model.py --prune_method sparsegpt --sparsity_ratio 0.10
# CUDA_VISIBLE_DEVICES=6 python compressed_model.py --prune_method sparsegpt --sparsity_ratio 0.20
# CUDA_VISIBLE_DEVICES=6 python compressed_model.py --prune_method sparsegpt --sparsity_ratio 0.30
# CUDA_VISIBLE_DEVICES=6 python compressed_model.py --prune_method sparsegpt --sparsity_ratio 0.40
# CUDA_VISIBLE_DEVICES=6 python compressed_model.py --prune_method sparsegpt --sparsity_ratio 0.50
# CUDA_VISIBLE_DEVICES=6 python compressed_model.py --prune_method sparsegpt --sparsity_ratio 0.60
# CUDA_VISIBLE_DEVICES=6 python compressed_model.py --prune_method sparsegpt --sparsity_ratio 0.15
# CUDA_VISIBLE_DEVICES=6 python compressed_model.py --prune_method sparsegpt --sparsity_ratio 0.25
# CUDA_VISIBLE_DEVICES=6 python compressed_model.py --prune_method sparsegpt --sparsity_ratio 0.35
# CUDA_VISIBLE_DEVICES=6 python compressed_model.py --prune_method sparsegpt --sparsity_ratio 0.45
# CUDA_VISIBLE_DEVICES=6 python compressed_model.py --prune_method sparsegpt --sparsity_ratio 0.55
# CUDA_VISIBLE_DEVICES=6 python compressed_model.py --prune_method sparsegpt --sparsity_ratio 0.65
# CUDA_VISIBLE_DEVICES=6 python compressed_model.py --prune_method sparsegpt --sparsity_ratio 0.70
# CUDA_VISIBLE_DEVICES=6 python compressed_model.py --prune_method sparsegpt --sparsity_ratio 0.75
# CUDA_VISIBLE_DEVICES=6 python compressed_model.py --prune_method sparsegpt --sparsity_ratio 0.80

# CUDA_VISIBLE_DEVICES=5 python compressed_model.py --prune_method magnitude --sparsity_ratio 0.00 
# CUDA_VISIBLE_DEVICES=5 python compressed_model.py --prune_method magnitude --sparsity_ratio 0.05
# CUDA_VISIBLE_DEVICES=5 python compressed_model.py --prune_method magnitude --sparsity_ratio 0.10
# CUDA_VISIBLE_DEVICES=5 python compressed_model.py --prune_method magnitude --sparsity_ratio 0.20
# CUDA_VISIBLE_DEVICES=5 python compressed_model.py --prune_method magnitude --sparsity_ratio 0.30
# CUDA_VISIBLE_DEVICES=5 python compressed_model.py --prune_method magnitude --sparsity_ratio 0.40
# CUDA_VISIBLE_DEVICES=5 python compressed_model.py --prune_method magnitude --sparsity_ratio 0.50
# CUDA_VISIBLE_DEVICES=5 python compressed_model.py --prune_method magnitude --sparsity_ratio 0.60
# CUDA_VISIBLE_DEVICES=5 python compressed_model.py --prune_method magnitude --sparsity_ratio 0.15
# CUDA_VISIBLE_DEVICES=5 python compressed_model.py --prune_method magnitude --sparsity_ratio 0.25
# CUDA_VISIBLE_DEVICES=5 python compressed_model.py --prune_method magnitude --sparsity_ratio 0.35
# CUDA_VISIBLE_DEVICES=5 python compressed_model.py --prune_method magnitude --sparsity_ratio 0.45
# CUDA_VISIBLE_DEVICES=5 python compressed_model.py --prune_method magnitude --sparsity_ratio 0.55
# CUDA_VISIBLE_DEVICES=5 python compressed_model.py --prune_method magnitude --sparsity_ratio 0.65
# CUDA_VISIBLE_DEVICES=5 python compressed_model.py --prune_method magnitude --sparsity_ratio 0.70
# CUDA_VISIBLE_DEVICES=5 python compressed_model.py --prune_method magnitude --sparsity_ratio 0.75
# CUDA_VISIBLE_DEVICES=5 python compressed_model.py --prune_method magnitude --sparsity_ratio 0.80

CUDA_VISIBLE_DEVICES=6 python compressed_model.py --prune_method magnitude --sparsity_ratio 0.50 --sparsity_type 2:4
CUDA_VISIBLE_DEVICES=6 python compressed_model.py --prune_method wanda --sparsity_ratio 0.50 --sparsity_type 2:4
CUDA_VISIBLE_DEVICES=6 python compressed_model.py --prune_method sparsegpt --sparsity_ratio 0.50 --sparsity_type 2:4